name: CI macOS

on: [pull_request]

# Cancel "duplicated" workflows triggered by pushes to internal
# branches with associated PRs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CMAKE_BUILD_PARALLEL_LEVEL: 4 # num threads for build

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: '**/requirements.txt'
    - run: pip install -r requirements.txt

    - name: Install dependencies
      run: |
        brew install openmpi adios2 || true

    # this is a workaround because homebrew's stable is hdf5 2.0.0 and cmake's
    # find_package(HDF5) doesn't properly determine HDF5_IS_PARALLEL
    # this *should* be fixed in cmake 4.3
    - name: Install hdf5 from old formula
      run: |
        mkdir -p $(brew --repository)/Library/Taps/user/repo
        curl -o $(brew --repository)/Library/Taps/user/repo/hdf5-mpi.rb https://raw.githubusercontent.com/Homebrew/homebrew-core/d03791212a4670e68f21c66939c5d348bc1d4bef/Formula/h/hdf5-mpi.rb
        brew install user/repo/hdf5-mpi

    - name: Install parthenon_tools
      run: |
        pip install scripts/python/packages/parthenon_tools

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build

    - name: Test
      run: |
        cd build
        ctest -LE mpi

    - uses: actions/upload-artifact@v4
      with:
        name: configure-log-unit-macos
        path: build/CMakeFiles/CMakeOutput.log
        retention-days: 3
