name: Check PR Dependencies
on: [pull_request]
jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    name: Required PRs Merged
    steps:
    - uses: gregsdennis/dependencies-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
